apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app-deployment
  namespace: ivolve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: yassminfadloun/your-app:22
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
