apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: ivolve
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007
